// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfnzzbimqbmqhzorazmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmbnp6YmltcWJtcWh6b3Jhem1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzQwMzUsImV4cCI6MjA1Nzk1MDAzNX0.v__g0d6SRcwATw_VkvPkFeom82EtdzfTEUNNKVnu73s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);